require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|

  config.vm.box = "openstack"
   config.vm.box_url = "https://github.com/ggiamarchi/vagrant-openstack/raw/master/source/dummy.box"

  config.ssh.shell = "bash"
  config.ssh.username = "stack"
  #config.ssh.private_key_path = ENV['OS_KEYPAIR_PRIVATE_KEY']

  config.vm.provider :openstack do |os|
    os.username = ENV['OS_USERNAME']
    os.password = ENV['OS_PASSWORD']
    os.tenant_name = ENV['OS_TENANT_NAME']
    os.openstack_auth_url = ENV['OS_AUTH_URL']
    os.openstack_compute_url = ENV['OS_COMPUTE_URL']
    os.openstack_network_url = ENV['OS_NETWORK_URL']
    os.region = ENV['OS_REGION']
    #os.keypair_name = ENV['OS_KEYPAIR_NAME']
  end

  # Devstack Compute
  config.vm.define "devstack-compute-1", primary: true do |compute|
   compute.vm.provider :openstack do |os|
     os.server_name = "devstack-compute-1"
     os.floating_ip = ENV['OS_FLOATING_IP2']
     os.flavor = ENV['OS_FLAVOR']
     os.image = ENV['OS_IMAGE']
     #os.networks = [ENV['OS_NETWORK']]
     os.networks = [
        {
          id: '4d977b28-b96e-48a7-b651-ef7aaed70ca7',
          address: '192.168.10.21'
        }]
   end
end

  # Install puppet  
  config.vm.provision "shell", path: "../puppet/scripts/bootstrap.sh"

  config.vm.provision "puppet" do |puppet|
      puppet.hiera_config_path = "../puppet/hiera.yaml"
      puppet.working_directory = "/vagrant/puppet"
      puppet.manifests_path = "../puppet/manifests"
      puppet.manifest_file  = "base.pp"
  end
    
  config.vm.provision "puppet" do |puppet|
      puppet.hiera_config_path = "../puppet/hiera.yaml"
      puppet.working_directory = "/vagrant/puppet"
      puppet.manifests_path = "../puppet/manifests"
      puppet.manifest_file  = "devstack-compute.pp"
  end
end
